// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhexlwOcusbhHkf6VcEiZlMK1m6Ey9fMg',
    appId: '1:604721769175:android:a5411bb1c029fe77355e92',
    messagingSenderId: '604721769175',
    projectId: 'streaker-58e8c',
    storageBucket: 'streaker-58e8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJpEmuufvharFrA8xP6mHtds8NwNM8zi0',
    appId: '1:604721769175:ios:6b4f335692e38707355e92',
    messagingSenderId: '604721769175',
    projectId: 'streaker-58e8c',
    storageBucket: 'streaker-58e8c.firebasestorage.app',
    iosClientId: '604721769175-18de53knoo6vav1r7g038utfm02scj03.apps.googleusercontent.com',
    iosBundleId: 'com.example.streaker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqfP8ZPwC3J7k9UChMkkpAi3uMQX70sf4',
    appId: '1:604721769175:web:fc5f032909a68855355e92',
    messagingSenderId: '604721769175',
    projectId: 'streaker-58e8c',
    authDomain: 'streaker-58e8c.firebaseapp.com',
    storageBucket: 'streaker-58e8c.firebasestorage.app',
  );

}